# Generated by Django 3.2.9 on 2021-11-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
