# Generated by Django 3.2.9 on 2021-11-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsapi', '0002_newsitem_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='imageurl',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
