# Generated by Django 3.2.9 on 2021-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapper',
            name='selecteddata',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
